repo: connorjclark/git3po-test-repo
startAt: 2017-01-01
pullRequests: true
filters:
  - type: issue
    criteria:
      state: open
      mergeable: true
  - type: label
    label: land-when-green
actions:
  - type: merge
    mergeMethod: squash
    message: ''
  - type: remove_label
    label: land-when-green
